### PR TITLE
added wasd-extended-numeric, wasd-extended-numeric-function-left presets

### PR DESCRIPTION
**Pull request by networkjanitor**
wasd-extended-numeric vs wasd-full:
	adds ALT
	adds Z, X, C, V, B, T, G
	adds 1, 2, 3, 4, 5

wasd-extended-numeric-function-left vs wasd-extended-numeric:
	adds F1, F2, F3, F4, F5 on the left side of the keyboard

### CODE REVIEW

**Comment by networkjanitor** [comment]
wasd-extended-numeric-preview:
wasd-extended-numeric-preview

wasd-extended-numeric-function-left-preview:
wasd-extended-numeric-function-left-preview

**Comment by univrsal** [comment]
Nice, thanks for the contribution. Btw did you build v5 yourself or did you use the builds I gave out for testing?

**Comment by univrsal** [comment]
Thanks for the contribution. I don't know what's up with github right now, but I did merge it.
Also did you build version 5 yourself or did you use one of the test builds?

**Comment by networkjanitor** [comment]
Used the build you gave out for testing.

**Comment by networkjanitor** [comment]
Used the build you gave out for testing.

**Pull request merged**
