### PR TITLE
Game kyuubi gamepad patch

### PR DESCRIPTION
**Pull request by GameKyuubi**
detect gamepads on linux

### CODE REVIEW

**Comment by univrsal** [comment]
What part specifically fixes gamepad detection? I only see some reformatting and log entries. Gamepads are detected fine for me already.

**Comment by univrsal** [comment]
That is just logging, it doesn't change the folder for gamepad discovery. libgamepad actually looks for gamepads in ``/dev/input/js*`` or ``/dev/input/by-id``. The log entry is just wrong.

**Comment by GameKyuubi** [comment]
Well that's embarrassing.  I have no idea why it wasn't working but it works now.  Thanks.

**Comment by univrsal** [comment]
No worries.

**Pull request closed without merging**
