### PR TITLE
Added Joy-Con Grip preset

### PR DESCRIPTION
**Pull request by TybaIt**
Made by me, Tybalt.

I made this for my [Temtem](https://crema.gg/games/temtem/) Stream ([twitch.tv\TamerTybalt](https://www.twitch.tv/TamerTybalt/))
but in case someone in this very universe is also using Joy-Con Grip to play specific games on PC using [BetterJoyForCemu](https://github.com/Davidobot/BetterJoyForCemu) or another driver I am happy to share my work with you.

**Preview**: Load Image Failure  

**Preview Animated**: [Gifv cannot be embedded (click)](https://i.imgur.com/QKUr7dV.gifv)  

I included the *.psd file so feel free to customize it to your liking.

### CODE REVIEW

**Comment by univrsal** [comment]
Thanks for your contribution! I'll also add it to the release archive once I get the time

**Comment by TybaIt** [comment]
What's the reason it needs to be archived if you do not mind me asking? :)

**Comment by univrsal** [comment]
I mean the zip archive that can be downloaded in the release section. It contains all presets, so I'd add yours in there unless you don't want it in there.

**Comment by TybaIt** [comment]
Go ahead! Oh no. I meant why the presets need to be archived.
-----
Ich meinte, warum die presets selber archiviert sein sollen?

**Comment by univrsal** [comment]
Spart platz

**Pull request merged**
