### PR TITLE
Valorant Presets

### PR DESCRIPTION
**Pull request by LocksmithArmy**
This update adds a wasd preset specifically for the game Valorant.
It also adds some more mouse presets that might be more appealing.

Finally it alters the mouse_highlight.html code to skip the first 0.0 point, so the mouse hopefully wont flicker back to center as much during gameplay.

### CODE REVIEW

**Comment by LocksmithArmy** [comment]
Added a wasd-valorant-micro that requires a spacebar that is smaller, so edited the wasd.png aswell.

**Comment by univrsal** [comment]
Looks fine to me but could you undo the changes in `mouse_highlight.html`? That file is an overlay that puts a red circle around the mouse cursor. It's not connected to issue with the flickering back to the center.

**Comment by LocksmithArmy** [comment]
Couldnt figure out how to remove part of the commit, so I just undid the changes manually.

One day Ill figure out that flicker ;)

**Comment by univrsal** [comment]
https://github.com/univrsal/input-overlay/blob/master/src/util/element/element_mouse_movement.cpp#L77-L102 would be where I'd start looking. I've tried to smooth the mouse movements before, but it didn't really help.

**Comment by univrsal** [comment]
Thanks for the presets!

**Comment by LocksmithArmy** [comment]
Thanks for the direction. Making presets is kinda fun :)

**Pull request merged**
